### ISSUE TITLE
GLFW wrap is not downloadable.

### ISSUE THREAD

**Issue by lufsc** [mesonbuild/mesonwrap#132]
The Button for `glfw3` is in the web-UI, but the page you get to just shows "Something went wrong - No such project". Is the wrap just unavaliable or unfinished, or is there something wrong with the site?

**Comment by legeana** [comment]
No one submitted a wrap: https://github.com/mesonbuild/glfw3/tree/3.3.2
There is a known bug: https://github.com/mesonbuild/mesonwrap/issues/130
