### ISSUE TITLE
Two new wraps to add

### ISSUE THREAD

**Issue by jpakkane** [mesonbuild/mesonwrap#136]
Docopt.cpp https://github.com/docopt/docopt.cpp/

Docopt.cpp's pkg-config name is just `docopt` so we should probably use that as well.

imgui-sfml: https://github.com/eliasdaler/imgui-sfml

**Comment by legeana** [comment]
Repository created: https://github.com/mesonbuild/docopt
Repository created: https://github.com/mesonbuild/imgui-sfml
